### ISSUE TITLE
KeyError: 2

### ISSUE THREAD

**Issue by ArtificialZeng** [WENGSYX/CirBERTa#2]
Traceback (most recent call last):
  File "F:/ctr_project/CirBERTa-main/baseline/Sohu2022/train_nlp.py", line 693, in <module>
    val_loss, val_acc, pred,y_truth = test_model(model, val_loader,epoch)
  File "F:/ctr_project/CirBERTa-main/baseline/Sohu2022/train_nlp.py", line 274, in test_model
    golds.append({125883:0,115270:1,68158:2,110093:3,64243:4}[i.cpu().item()])
KeyError: 2

**Comment by WENGSYX** [comment]
已修复train_nlp.py

**Comment by ArtificialZeng** [comment]
> 已修复train_nlp.py

写论文准备投哪里呀， ？
